class Municipality:
    def __init__(self, id, name):
        self.id = id
        self.name = name


class Municipalities:
    def __init__(self):
        self.by_id = {}
        self.by_name = {}

    def add(self, municipality):
        self.by_id[municipality.id] = municipality
        self.by_name[municipality.name] = municipality

    def get_by_id(self, id):
        return self.by_id.get(id)

    def get_by_name(self, name):
        return self.by_name.get(name)


municipalities = Municipalities()

municipalities.add(Municipality(1, "Arica"))
municipalities.add(Municipality(2, "Aisén"))
municipalities.add(Municipality(3, "Algarrobo"))
municipalities.add(Municipality(4, "Alhué"))
municipalities.add(Municipality(5, "Alto Biobío"))
municipalities.add(Municipality(6, "Alto del Carmen"))
municipalities.add(Municipality(7, "Alto Hospicio"))
municipalities.add(Municipality(8, "Ancud"))
municipalities.add(Municipality(9, "Andacollo"))
municipalities.add(Municipality(10, "Angol"))
municipalities.add(Municipality(11, "Antártica"))
municipalities.add(Municipality(12, "Antofagasta"))
municipalities.add(Municipality(13, "Antuco"))
municipalities.add(Municipality(14, "Arauco"))
municipalities.add(Municipality(15, "Buin"))
municipalities.add(Municipality(16, "Bulnes"))
municipalities.add(Municipality(17, "Cabildo"))
municipalities.add(Municipality(18, "Cabo de Hornos"))
municipalities.add(Municipality(19, "Cabrero"))
municipalities.add(Municipality(20, "Calama"))
municipalities.add(Municipality(21, "Calbuco"))
municipalities.add(Municipality(22, "Caldera"))
municipalities.add(Municipality(23, "Calera"))
municipalities.add(Municipality(24, "Calera de Tango"))
municipalities.add(Municipality(25, "Calle Larga"))
municipalities.add(Municipality(26, "Camarones"))
municipalities.add(Municipality(27, "Camiña"))
municipalities.add(Municipality(28, "Canela"))
municipalities.add(Municipality(29, "Cañete"))
municipalities.add(Municipality(30, "Carahue"))
municipalities.add(Municipality(31, "Cartagena"))
municipalities.add(Municipality(32, "Casablanca"))
municipalities.add(Municipality(33, "Castro"))
municipalities.add(Municipality(34, "Catemu"))
municipalities.add(Municipality(35, "Cauquenes"))
municipalities.add(Municipality(36, "Cerrillos"))
municipalities.add(Municipality(37, "Cerro Navia"))
municipalities.add(Municipality(38, "Chaitén"))
municipalities.add(Municipality(39, "Chanco"))
municipalities.add(Municipality(40, "Chañaral"))
municipalities.add(Municipality(41, "Chépica"))
municipalities.add(Municipality(42, "Chiguayante"))
municipalities.add(Municipality(43, "Chile Chico"))
municipalities.add(Municipality(44, "Chillán"))
municipalities.add(Municipality(45, "Chillán Viejo"))
municipalities.add(Municipality(46, "Chimbarongo"))
municipalities.add(Municipality(47, "Cholchol"))
municipalities.add(Municipality(48, "Chonchi"))
municipalities.add(Municipality(49, "Cisnes"))
municipalities.add(Municipality(50, "Cobquecura"))
municipalities.add(Municipality(51, "Cochamó"))
municipalities.add(Municipality(52, "Cochrane"))
municipalities.add(Municipality(53, "Codegua"))
municipalities.add(Municipality(54, "Coelemu"))
municipalities.add(Municipality(55, "Coihaique"))
municipalities.add(Municipality(56, "Coihueco"))
municipalities.add(Municipality(57, "Coinco"))
municipalities.add(Municipality(58, "Colbún"))
municipalities.add(Municipality(59, "Colchane"))
municipalities.add(Municipality(60, "Colina"))
municipalities.add(Municipality(61, "Collipulli"))
municipalities.add(Municipality(62, "Coltauco"))
municipalities.add(Municipality(63, "Combarbalá"))
municipalities.add(Municipality(64, "Concepción"))
municipalities.add(Municipality(65, "Conchalí"))
municipalities.add(Municipality(66, "Concón"))
municipalities.add(Municipality(67, "Constitución"))
municipalities.add(Municipality(68, "Contulmo"))
municipalities.add(Municipality(69, "Copiapó"))
municipalities.add(Municipality(70, "Coquimbo"))
municipalities.add(Municipality(71, "Coronel"))
municipalities.add(Municipality(72, "Corral"))
municipalities.add(Municipality(73, "Cunco"))
municipalities.add(Municipality(74, "Curacautín"))
municipalities.add(Municipality(75, "Curacaví"))
municipalities.add(Municipality(76, "Curaco de Vélez"))
municipalities.add(Municipality(77, "Curanilahue"))
municipalities.add(Municipality(78, "Curarrehue"))
municipalities.add(Municipality(79, "Curepto"))
municipalities.add(Municipality(80, "Curicó"))
municipalities.add(Municipality(81, "Dalcahue"))
municipalities.add(Municipality(82, "Diego de Almagro"))
municipalities.add(Municipality(83, "Doñihue"))
municipalities.add(Municipality(84, "El Bosque"))
municipalities.add(Municipality(85, "El Carmen"))
municipalities.add(Municipality(86, "El Monte"))
municipalities.add(Municipality(87, "El Quisco"))
municipalities.add(Municipality(88, "El Tabo"))
municipalities.add(Municipality(89, "Empedrado"))
municipalities.add(Municipality(90, "Ercilla"))
municipalities.add(Municipality(91, "Estación Central"))
municipalities.add(Municipality(92, "Florida"))
municipalities.add(Municipality(93, "Freire"))
municipalities.add(Municipality(94, "Freirina"))
municipalities.add(Municipality(95, "Fresia"))
municipalities.add(Municipality(96, "Frutillar"))
municipalities.add(Municipality(97, "Futaleufú"))
municipalities.add(Municipality(98, "Futrono"))
municipalities.add(Municipality(99, "Galvarino"))
municipalities.add(Municipality(100, "General Lagos"))
municipalities.add(Municipality(101, "Gorbea"))
municipalities.add(Municipality(102, "Graneros"))
municipalities.add(Municipality(103, "Guaitecas"))
municipalities.add(Municipality(104, "Hijuelas"))
municipalities.add(Municipality(105, "Hualaihué"))
municipalities.add(Municipality(106, "Hualañé"))
municipalities.add(Municipality(107, "Hualpén"))
municipalities.add(Municipality(108, "Hualqui"))
municipalities.add(Municipality(109, "Huara"))
municipalities.add(Municipality(110, "Huasco"))
municipalities.add(Municipality(111, "Huechuraba"))
municipalities.add(Municipality(112, "Illapel"))
municipalities.add(Municipality(113, "Independencia"))
municipalities.add(Municipality(114, "Iquique"))
municipalities.add(Municipality(115, "Isla de Pascua"))
municipalities.add(Municipality(116, "Isla de Maipo"))
municipalities.add(Municipality(117, "Juan Fernández"))
municipalities.add(Municipality(118, "La Cisterna"))
municipalities.add(Municipality(119, "La Cruz"))
municipalities.add(Municipality(120, "La Estrella"))
municipalities.add(Municipality(121, "La Florida"))
municipalities.add(Municipality(122, "La Granja"))
municipalities.add(Municipality(123, "La Higuera"))
municipalities.add(Municipality(124, "La Ligua"))
municipalities.add(Municipality(125, "La Pintana"))
municipalities.add(Municipality(126, "La Reina"))
municipalities.add(Municipality(127, "La Serena"))
municipalities.add(Municipality(128, "La Unión"))
municipalities.add(Municipality(129, "Lago Ranco"))
municipalities.add(Municipality(130, "Lago Verde"))
municipalities.add(Municipality(131, "Laguna Blanca"))
municipalities.add(Municipality(132, "Laja"))
municipalities.add(Municipality(133, "Lampa"))
municipalities.add(Municipality(134, "Lanco"))
municipalities.add(Municipality(135, "Las Cabras"))
municipalities.add(Municipality(136, "Las Condes"))
municipalities.add(Municipality(137, "Lautaro"))
municipalities.add(Municipality(138, "Lebu"))
municipalities.add(Municipality(139, "Licantén"))
municipalities.add(Municipality(140, "Limache"))
municipalities.add(Municipality(141, "Linares"))
municipalities.add(Municipality(142, "Litueche"))
municipalities.add(Municipality(143, "Llaillay"))
municipalities.add(Municipality(144, "Llanquihue"))
municipalities.add(Municipality(145, "Lo Barnechea"))
municipalities.add(Municipality(146, "Lo Espejo"))
municipalities.add(Municipality(147, "Lo Prado"))
municipalities.add(Municipality(148, "Lolol"))
municipalities.add(Municipality(149, "Loncoche"))
municipalities.add(Municipality(150, "Longaví"))
municipalities.add(Municipality(151, "Lonquimay"))
municipalities.add(Municipality(152, "Los Álamos"))
municipalities.add(Municipality(153, "Los Andes"))
municipalities.add(Municipality(154, "Los Ángeles"))
municipalities.add(Municipality(155, "Los Lagos"))
municipalities.add(Municipality(156, "Los Muermos"))
municipalities.add(Municipality(157, "Los Sauces"))
municipalities.add(Municipality(158, "Los Vilos"))
municipalities.add(Municipality(159, "Lota"))
municipalities.add(Municipality(160, "Lumaco"))
municipalities.add(Municipality(161, "Machalí"))
municipalities.add(Municipality(162, "Macul"))
municipalities.add(Municipality(163, "Máfil"))
municipalities.add(Municipality(164, "Maipú"))
municipalities.add(Municipality(165, "Malloa"))
municipalities.add(Municipality(166, "Marchihue"))
municipalities.add(Municipality(167, "María Elena"))
municipalities.add(Municipality(168, "María Pinto"))
municipalities.add(Municipality(169, "Mariquina"))
municipalities.add(Municipality(170, "Maule"))
municipalities.add(Municipality(171, "Maullín"))
municipalities.add(Municipality(172, "Mejillones"))
municipalities.add(Municipality(173, "Melipeuco"))
municipalities.add(Municipality(174, "Melipilla"))
municipalities.add(Municipality(175, "Molina"))
municipalities.add(Municipality(176, "Monte Patria"))
municipalities.add(Municipality(177, "Mostazal"))
municipalities.add(Municipality(178, "Mulchén"))
municipalities.add(Municipality(179, "Nacimiento"))
municipalities.add(Municipality(180, "Nancagua"))
municipalities.add(Municipality(181, "Natales"))
municipalities.add(Municipality(182, "Navidad"))
municipalities.add(Municipality(183, "Negrete"))
municipalities.add(Municipality(184, "Ninhue"))
municipalities.add(Municipality(185, "Nogales"))
municipalities.add(Municipality(186, "Nueva Imperial"))
municipalities.add(Municipality(187, "Ñiquén"))
municipalities.add(Municipality(188, "Ñuñoa"))
municipalities.add(Municipality(189, "O'Higgins"))
municipalities.add(Municipality(190, "Olivar"))
municipalities.add(Municipality(191, "Ollagüe"))
municipalities.add(Municipality(192, "Olmué"))
municipalities.add(Municipality(193, "Osorno"))
municipalities.add(Municipality(194, "Ovalle"))
municipalities.add(Municipality(195, "Padre Hurtado"))
municipalities.add(Municipality(196, "Padre Las Casas"))
municipalities.add(Municipality(197, "Paiguano"))
municipalities.add(Municipality(198, "Paillaco"))
municipalities.add(Municipality(199, "Paine"))
municipalities.add(Municipality(200, "Palena"))
municipalities.add(Municipality(201, "Palmilla"))
municipalities.add(Municipality(202, "Panguipulli"))
municipalities.add(Municipality(203, "Panquehue"))
municipalities.add(Municipality(204, "Papudo"))
municipalities.add(Municipality(205, "Paredones"))
municipalities.add(Municipality(206, "Parral"))
municipalities.add(Municipality(207, "Pedro Aguirre Cerda"))
municipalities.add(Municipality(208, "Pelarco"))
municipalities.add(Municipality(209, "Pelluhue"))
municipalities.add(Municipality(210, "Pemuco"))
municipalities.add(Municipality(211, "Pencahue"))
municipalities.add(Municipality(212, "Penco"))
municipalities.add(Municipality(213, "Peñaflor"))
municipalities.add(Municipality(214, "Peñalolén"))
municipalities.add(Municipality(215, "Peralillo"))
municipalities.add(Municipality(216, "Perquenco"))
municipalities.add(Municipality(217, "Petorca"))
municipalities.add(Municipality(218, "Peumo"))
municipalities.add(Municipality(219, "Pica"))
municipalities.add(Municipality(220, "Pichidegua"))
municipalities.add(Municipality(221, "Pichilemu"))
municipalities.add(Municipality(222, "Pinto"))
municipalities.add(Municipality(223, "Pirque"))
municipalities.add(Municipality(224, "Pitrufquén"))
municipalities.add(Municipality(225, "Placilla"))
municipalities.add(Municipality(226, "Portezuelo"))
municipalities.add(Municipality(227, "Porvenir"))
municipalities.add(Municipality(228, "Pozo Almonte"))
municipalities.add(Municipality(229, "Primavera"))
municipalities.add(Municipality(230, "Providencia"))
municipalities.add(Municipality(231, "Puchuncaví"))
municipalities.add(Municipality(232, "Pucón"))
municipalities.add(Municipality(233, "Pudahuel"))
municipalities.add(Municipality(234, "Puente Alto"))
municipalities.add(Municipality(235, "Puerto Montt"))
municipalities.add(Municipality(236, "Puerto Octay"))
municipalities.add(Municipality(237, "Puerto Varas"))
municipalities.add(Municipality(238, "Pumanque"))
municipalities.add(Municipality(239, "Punitaqui"))
municipalities.add(Municipality(240, "Punta Arenas"))
municipalities.add(Municipality(241, "Puqueldón"))
municipalities.add(Municipality(242, "Purén"))
municipalities.add(Municipality(243, "Purranque"))
municipalities.add(Municipality(244, "Putaendo"))
municipalities.add(Municipality(245, "Putre"))
municipalities.add(Municipality(246, "Puyehue"))
municipalities.add(Municipality(247, "Queilén"))
municipalities.add(Municipality(248, "Quellón"))
municipalities.add(Municipality(249, "Quemchi"))
municipalities.add(Municipality(250, "Quilaco"))
municipalities.add(Municipality(251, "Quilicura"))
municipalities.add(Municipality(252, "Quilleco"))
municipalities.add(Municipality(253, "Quillón"))
municipalities.add(Municipality(254, "Quillota"))
municipalities.add(Municipality(255, "Quilpué"))
municipalities.add(Municipality(256, "Quinchao"))
municipalities.add(Municipality(257, "Quinta de Tilcoco"))
municipalities.add(Municipality(258, "Quinta Normal"))
municipalities.add(Municipality(259, "Quintero"))
municipalities.add(Municipality(260, "Quirihue"))
municipalities.add(Municipality(261, "Rancagua"))
municipalities.add(Municipality(262, "Ránquil"))
municipalities.add(Municipality(263, "Rauco"))
municipalities.add(Municipality(264, "Recoleta"))
municipalities.add(Municipality(265, "Renaico"))
municipalities.add(Municipality(266, "Renca"))
municipalities.add(Municipality(267, "Rengo"))
municipalities.add(Municipality(268, "Requínoa"))
municipalities.add(Municipality(269, "Retiro"))
municipalities.add(Municipality(270, "Rinconada"))
municipalities.add(Municipality(271, "Río Bueno"))
municipalities.add(Municipality(272, "Río Claro"))
municipalities.add(Municipality(273, "Río Hurtado"))
municipalities.add(Municipality(274, "Río Ibáñez"))
municipalities.add(Municipality(275, "Río Negro"))
municipalities.add(Municipality(276, "Río Verde"))
municipalities.add(Municipality(277, "Romeral"))
municipalities.add(Municipality(278, "Saavedra"))
municipalities.add(Municipality(279, "Sagrada Familia"))
municipalities.add(Municipality(280, "Salamanca"))
municipalities.add(Municipality(281, "San Antonio"))
municipalities.add(Municipality(282, "San Bernardo"))
municipalities.add(Municipality(283, "San Carlos"))
municipalities.add(Municipality(284, "San Clemente"))
municipalities.add(Municipality(285, "San Esteban"))
municipalities.add(Municipality(286, "San Fabián"))
municipalities.add(Municipality(287, "San Felipe"))
municipalities.add(Municipality(288, "San Fernando"))
municipalities.add(Municipality(289, "San Gregorio"))
municipalities.add(Municipality(290, "San Ignacio"))
municipalities.add(Municipality(291, "San Javier"))
municipalities.add(Municipality(292, "San Joaquín"))
municipalities.add(Municipality(293, "San José de Maipo"))
municipalities.add(Municipality(294, "San Juan de la Costa"))
municipalities.add(Municipality(295, "San Miguel"))
municipalities.add(Municipality(296, "San Nicolás"))
municipalities.add(Municipality(297, "San Pablo"))
municipalities.add(Municipality(298, "San Pedro"))
municipalities.add(Municipality(299, "San Pedro de Atacama"))
municipalities.add(Municipality(300, "San Pedro de la Paz"))
municipalities.add(Municipality(301, "San Rafael"))
municipalities.add(Municipality(302, "San Ramón"))
municipalities.add(Municipality(303, "San Rosendo"))
municipalities.add(Municipality(304, "San Vicente"))
municipalities.add(Municipality(305, "Santa Bárbara"))
municipalities.add(Municipality(306, "Santa Cruz"))
municipalities.add(Municipality(307, "Santa Juana"))
municipalities.add(Municipality(308, "Santa María"))
municipalities.add(Municipality(309, "Santiago"))
municipalities.add(Municipality(310, "Santo Domingo"))
municipalities.add(Municipality(311, "Sierra Gorda"))
municipalities.add(Municipality(312, "Talagante"))
municipalities.add(Municipality(313, "Talca"))
municipalities.add(Municipality(314, "Talcahuano"))
municipalities.add(Municipality(315, "Taltal"))
municipalities.add(Municipality(316, "Temuco"))
municipalities.add(Municipality(317, "Teno"))
municipalities.add(Municipality(318, "Teodoro Schmidt"))
municipalities.add(Municipality(319, "Tierra Amarilla"))
municipalities.add(Municipality(320, "Tiltil"))
municipalities.add(Municipality(321, "Timaukel"))
municipalities.add(Municipality(322, "Tirúa"))
municipalities.add(Municipality(323, "Tocopilla"))
municipalities.add(Municipality(324, "Toltén"))
municipalities.add(Municipality(325, "Tomé"))
municipalities.add(Municipality(326, "Torres del Paine"))
municipalities.add(Municipality(327, "Tortel"))
municipalities.add(Municipality(328, "Traiguén"))
municipalities.add(Municipality(329, "Treguaco"))
municipalities.add(Municipality(330, "Tucapel"))
municipalities.add(Municipality(331, "Valdivia"))
municipalities.add(Municipality(332, "Vallenar"))
municipalities.add(Municipality(333, "Valparaíso"))
municipalities.add(Municipality(334, "Vichuquén"))
municipalities.add(Municipality(335, "Victoria"))
municipalities.add(Municipality(336, "Vicuña"))
municipalities.add(Municipality(337, "Vilcún"))
municipalities.add(Municipality(338, "Villa Alegre"))
municipalities.add(Municipality(339, "Villa Alemana"))
municipalities.add(Municipality(340, "Villarrica"))
municipalities.add(Municipality(341, "Viña del Mar"))
municipalities.add(Municipality(342, "Vitacura"))
municipalities.add(Municipality(343, "Yerbas Buenas"))
municipalities.add(Municipality(344, "Yumbel"))
municipalities.add(Municipality(345, "Yungay"))
municipalities.add(Municipality(346, "Zapallar"))
